[deps]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
BesselK = "432ab697-7a72-484f-bc4a-bc531f5c819b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GALAHAD = "c591611e-c43e-4808-98fb-ce4cafe3a717"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
UnoSolver = "1baa60ac-02f7-4b39-a7a8-2f4f58486b05"
Vecchia = "8d73829f-f4b0-474a-9580-cecc8e084068"
