name = "Vecchia"
uuid = "8d73829f-f4b0-474a-9580-cecc8e084068"
authors = ["Chris Geoga <geoga@wisc.edu>", "Florian Schafer <florian.schaefer@nyu.edu>"]
version = "0.10.4"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
HNSW = "540f64fa-c57e-11e8-081c-41422cda4629"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GALAHAD = "c591611e-c43e-4808-98fb-ce4cafe3a717"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[extensions]
VecchiaGALAHADExt = ["GALAHAD", "ForwardDiff"]
VecchiaJuMPExt = ["JuMP", "ForwardDiff"]

[compat]
Accessors = "0.1.42"
Distances = "0.10.12"
HNSW = "0.1.5"
NearestNeighbors = "0.4"
Random = "1.11.0"
StaticArrays = "1"
julia = "1"
