name = "Vecchia"
uuid = "8d73829f-f4b0-474a-9580-cecc8e084068"
version = "0.12.6"
authors = ["Chris Geoga <geoga@wisc.edu>"]

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
HNSW = "540f64fa-c57e-11e8-081c-41422cda4629"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"

[weakdeps]
BesselK = "432ab697-7a72-484f-bc4a-bc531f5c819b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeometricalPredicates = "fd0ad045-b25c-564e-8f9c-8ef5c5f21267"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnoSolver = "1baa60ac-02f7-4b39-a7a8-2f4f58486b05"
sequentialknn_jll = "a3d66c5c-fa88-5e7c-8b67-86d01549c065"

[extensions]
VecchiaForwardDiffExt = ["ForwardDiff"]
VecchiaGeometricalPredicatesExt = ["GeometricalPredicates"]
VecchiaNLPModelsExt = ["NLPModels", "ForwardDiff"]
VecchiaUnoSolverExt = ["NLPModels", "ForwardDiff", "UnoSolver"]
VecchiasequentialknnExt = ["sequentialknn_jll"]

[compat]
BesselK = "0.5.7"
Distances = "0.10.12"
HNSW = "0.1.6"
NLPModels = "0.21.6"
Random = "1.10"
StableRNGs = "1"
StaticArrays = "1"
StaticArraysCore = "1"
UnoSolver = "0.1.7"
julia = "1.10"
sequentialknn_jll = "0.2"

[targets]
test = ["Test", "BesselK", "StaticArrays", "StableRNGs"]
